sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - cd docs/doxygen
  - doxygen

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/doxygen/1.0.2
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
