#!/bin/bash
if [ "X$1" == "X" ] ; then
    agent null file_192.168.201.2
elif [ "X$2" == "X" ] ; then
    agent null file_192.168.201.2 "$1 $2"
elif [ "X$3" == "X" ] ; then
    agent null file_192.168.201.2 "$1 $2"
elif [ "X$3" == "X" ] ; then
    agent null file_192.168.201.2 "$1 $2 $3"
elif [ "X$4" == "X" ] ; then
    agent null file_192.168.201.2 "$1 $2 $3 $4"
elif [ "X$5" == "X" ] ; then
    agent null file_192.168.201.2 "$1 $2 $3 $4 $5"
elif [ "X$6" == "X" ] ; then
    agent null file_192.168.201.2 "$1 $2 $3 $4 $5 $6"
elif [ "X$7" == "X" ] ; then
    agent null file_192.168.201.2 "$1 $2 $3 $4 $5 $6 $7"
elif [ "X$8" == "X" ] ; then
    agent null file_192.168.201.2 "$1 $2 $3 $4 $5 $6 $7 $8"
elif [ "X$9" == "X" ] ; then
    agent null file_192.168.201.2 "$1 $2 $3 $4 $5 $6 $7 $8 $9"
fi
