#!/bin/bash
mkdir -p $COSMOS/log

#finally start agent antenna
agent_antenna $1 $2 >> $COSMOS/log/agent_antenna_$2.log 2>&1 &
echo "agent_antenna started for $1:$2"

# Exit 0 for rc.local success
exit 0


