#!/bin/bash
if [ "X$2" = "X" ] ; then
    agent kauaicc $1
elif [ "X$3" = "X" ] ; then
    agent kauaicc $1 "$2"
elif [ "X$3" = "X" ] ; then
    agent kauaicc $1 "$2 $3"
elif [ "X$4" = "X" ] ; then
    agent kauaicc $1 "$2 $3 $4"
elif [ "X$5" = "X" ] ; then
    agent kauaicc $1 "$2 $3 $4 $5"
elif [ "X$6" = "X" ] ; then
    agent kauaicc $1 "$2 $3 $4 $5 $6"
elif [ "X$7" = "X" ] ; then
    agent kauaicc $1 "$2 $3 $4 $5 $6 $7"
elif [ "X$8" = "X" ] ; then
    agent kauaicc $1 "$2 $3 $4 $5 $6 $7 $8"
elif [ "X$9" = "X" ] ; then
    agent kauaicc $1 "$2 $3 $4 $5 $6 $7 $8 $9"
elif [ "X${10}" = "X" ] ; then
    agent kauaicc $1 "$2 $3 $4 $5 $6 $7 $8 $9 ${10}"
elif [ "X${11}" = "X" ] ; then
    agent kauaicc $1 "$2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11}"
elif [ "X${12}" = "X" ] ; then
    agent kauaicc $1 "$2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12}"
fi
