# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build and Test (Linux)

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  BUILD_TYPE: Release
  CROSS_TYPE: linux

jobs:
  build-and-test:
    runs-on: arc-runner-set
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential git

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build/linux -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCROSS_TYPE=${{env.CROSS_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build/linux --config ${{env.BUILD_TYPE}}

    - name: Run CTest
      working-directory: ${{github.workspace}}/build/linux
      run: ctest -C ${{env.BUILD_TYPE}}
